### ISSUE TITLE
Debug of ConfigReader

### ISSUE THREAD

**Issue by ksabochick** [maine-cyber/mcsc-unisim#63]
## Current Debugging Results for ConfigReader
_January 3rd 2017_

### Warning Messages/Terminations
The following cases should return warning messages or terminate the program.

- [x] 1. **default:**  When a parameter falls back to default, there should be a note (lowest level of message) that notifies the user.

- [x] 2. **multiple definitions:**  When the config file contains multiple definitions for a parameter, such as `time = "noon"; time = "12:00"`, there should be an error. ConfigReader currently accesses the last assigned value. If the parameter is in the default, the assignment should fall back to default with a warning error message. If the parameter is not in the default, the program should terminate.

- [x] 3. **special parameters:** There are three cases that should not be permitted to be parameters in a config file: "true", "false", and "null". Use of these cases should produce an error similar to that of an illegal character or number.

- [x] 4. **improper casting:** There are certain cases that might necessitate error messages or terminations. For example, if a user attempts to access the value of the parameter "age" using `getInt("age")` and the value in the config file is a string (say "age = "nine""), it returns 0. It may or may not be possible to check for a proper value in the _default_ config before resorting to returning 0 for improper casting (say, if the value in the default was "age = 9").

- [x] 5. **non-existing parameter:** If a parameter is not in the config file and not in the default, when the user attempts to access it the value returns as the empty value depending on the accessor (0 for getInt(), "" for getString(), etc). This case might necessitate a warning of a non-existent parameter (though this may be taken care of in the ConfigObject update).

### Fixes and Cleanups
Some general fixes and cleanups discussed:

- [x] 1. Fix the way illegal characters are detected (use switch statement instead of multiple "or"s)

- [x] 2. Create a standard template for error messages (this applies to the entire toolkit)

- [x] 3. For types in general - currently, if you assign a value with two decimal points and try to retrieve it as a float, it returns the first decimal point and drops the second and all trailing after it. For example,  for `num = 0.001.1; return getFloat(num);` returns 0.001.

### TODO Statements
Some TODO statements were found in the existing ConfigReader source code.

- [x] 1. **Line 548:** In handleValue(), there is a TODO statement at the end of the string value checking if statement for adding proper validation.

- [x] 2. **Line 551:** In handleValue(), there is a TODO statement to add list handling for values. The current incomplete code contains `if( curr == '{' ) {}`

- [x] 3. **Line 606:** At the very end of handleValue(), there is a TODO statement for end-of-statement cleanup.

**Comment by stormecharette** [comment]
# Super Update  

Alrighty, I have addressed all of your reports and suggestions. Here is the breakdown in order:  

### Warning Messages etc.   

1. & 2. **default/redefs:** Instead of a note I added a warning when a parameter is overwritten during reading. I actually added two messages, one in `ConfigObject` for when you're using it on its own, and a different, more complicated one in `ConfigReader`. In `ConfigReader`, if a parameter is about to be overwritten, there is a check for an existing default. If there is a default, that is used as the overwritten value *every time an overwrite occurs for that parameter*. So you could overwrite it a million times in a file and the result would just be the default. If there is no default, it is hard overwritten. The logs reflect exactly what occurred.  

3. **special parameters:** This bug has been fixed.  

4. **improper casting:** This feature remains, you should always check the type of a parameter before casting with an accessor.  

5. **nonexistent parameter:** For now I have decided to omit log messages when a requested parameter doesn't exist. Developers can provide their own specific error messages based on the existence of an element. If this becomes a problem it can be added later.  

### Fixes & cleanups  

1. Fixed.  

2. I fixed all of the error messages so they are much more readable and consistent. 

3. Fixed.  

### TODO statements.  

I've removed all TODO and REMOVE statements thank goodness.  

## Other features and changes  

I added more control infrastructure to the reader so that the code is cleaner. This also fixed some bugs that were going unnoticed. These fixes may have also introduced new bugs, so I would I appreciate some help with additional testing, especially with malformed integral constants and param-to-param assignments.  

***IMPORTANT***: I changed the name of the function `ConfigObject::exists()` to `ConfigObject::contains()`. I completely removed `exists`, so the new code is **NOT backwards compatable**. If you were using `exists` anywhere in your code, change it to `contains`.   

I also added a new public inline function `isType` which takes a parameter and a `ConfigObject::Value::Type` and tells you if the value is of that type. This is shorthand for `param & type`, and is helpful for people who are not comfortable with bitwise operations. It also makes code more clear. You can OR multiple `sk::Type`s to test for multiple types at once.   

This update also fixes some internal issues in `ConfigObject` so it is more flexible when used standalone.

**Comment by stormecharette** [comment]
# :rotating_light: New bugs :rotating_light:  

Alright, this issue isn't fixed. The new system for checking overwrites while reading is totally broken. I need to take more time to fix it thoroughly. I will post an update when the config reader is fixed and I've tested it properly.

**Comment by stormecharette** [comment]
Should be fine now, but the reader is a mess anyway. Might be something to greatly simplify in the future. Someone could rewrite it to be much more basic and less bug-prone. It's a bit over engineered, my bad.
